
#mqttHost = config.getValue("mqtthostname", "localhost")
#myHostname = config.getValue("hostname", socket.gethostname())
#hostmqtt = mqtt.MQTT(mqttHost, myHostname, "relay_from")
#hostmqtt.loop_start()   # use the background thread
#master_mqtt_host = config.getValue("mqttmaster", "mqtt.thegame.folly.site")

# set hostname to override the automatic setting from host
#hostname: onceler

# use this setting if things need to work with bad internet connectivity
mqtthostname: "localhost"
mqttmaster: "mqtt.thegame.folly.site"

#good internet connectivity
#mqtthostname: "mqtt.thegame.folly.site"
#mqttmaster: ""

deployments:
  megagame:
    # relay only needed if using poor internet
    #relay_from:
    #  type: mqtt
    ping:
      type: ping
    # not yet (causes perf issues)
    #audio:
    #  type: audio
    #  pins: [18, 19, 21]
    rfid-nfc:
      type: rfid-mifare
    neopixel-status:
      type: neopixels
      led-count: 1
      led-pin: 12
      pins: [12]
    neopixel-level:
      type: neopixels
      led-count: 16
      led-pin: 13
      pins: [13]
hosts:
  one:
    type: megagame
  two:
    type: megagame
  yoga260:
    type: megagame

