
#mqttHost = config.getValue("mqtthostname", "localhost")
#myHostname = config.getValue("hostname", socket.gethostname())
#hostmqtt = mqtt.MQTT(mqttHost, myHostname, "relay_from")
#hostmqtt.loop_start()   # use the background thread
#master_mqtt_host = config.getValue("mqttmaster", "mqtt.thegame.folly.site")

# set hostname to override the automatic setting from host
#hostname: onceler

mqtthostname: "localhost"
mqttmaster: "mqtt.thegame.folly.site"

deployments:
  megagame:
    relay_from:
      type: mqtt
    audio:
      type: audio
      pins: [18, 19, 21]
    rfid-nfc:
      type: rfid-mifare
    neopixel-status:
      type: neopixels
      led-count: 1
      led-pin: 12
      pins: [12]
    neopixel-level:
      type: neopixels
      led-count: 16
      led-pin: 13
      pins: [13]
hosts:
  one:
    type: megagame
  yoga260:
    type: megagame

